target = ["esp32s3"]
idf_versions = ["v6.1"]
tools_json_file = "tools/tools.json"
config_file_save_path = "eim_config.toml"
non_interactive = true
wizard_all_questions = false
mirror = "https://dl.espressif.cn/github_assets"
idf_mirror = "https://git.espressif.com.cn"
pypi_mirror = "https://pypi.tuna.tsinghua.edu.cn/simple"
recurse_submodules = true
install_all_prerequisites = false
skip_prerequisites_check = false
cleanup = true
skip_components_download = false
python_env_folder_name = "python"
python_version_override = "python313"
create_bat_activation_script = false

[idf_features_per_version]
"v6.1" = ["core", "test-specific", "ci", "ide", "mcp", "docs"]

[idf_tools_per_version]
"v6.1" = ["xtensa-esp-elf-gdb", "xtensa-esp-elf", "esp-clang", "esp-clang-libs", "riscv32-esp-elf", "esp32ulp-elf", "openocd-esp32", "ninja", "esp-rom-elfs", "esp-clangd", "cmake"]
